{% set version = "3.0.2.0" %}
{% set name = "planarity" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/graph-algorithms/edge-addition-planarity-suite/archive/Version_{{ version }}.tar.gz
  sha256: 40f4ee7bbd5d8535460c60fc0fc1f806b10909a1419618fd9235746a420a04c6
  patches:
    # variables declared in headers should be marked extern
    - dllexport.patch       # [win]
    - exclude-unistd.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('planarity', max_pin='x.x.x') }}

requirements:
  build:
    - libtool      # [unix]
    - automake     # [unix]
    - autoconf     # [unix]
    - {{ compiler('c') }}
    - cmake        # [win]
    - make         # [unix]
  host:

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h   # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.a               # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib           # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so              # [linux]
    - if not exist %LIBRARY_LIB%/{{ name }}.lib exit 1    # [win]
    - if not exist %LIBRARY_INC%/{{ name }}/{{ name }}.h exit 1    # [win]
    - planarity -h | exit 0

about:
  home: https://github.com/graph-algorithms/edge-addition-planarity-suite
  license: BS 3-Clause
  license_file: LICENSE.TXT
  summary: |
    This code project provides a library for implementing graph algorithms as well
    as implementations of several planarity-related graph algorithms
  dev_url: https://github.com/graph-algorithms/edge-addition-planarity-suite

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
